package com.demo.entities;
// Generated Jan 20, 2022, 9:21:20 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExportInvoice generated by hbm2java
 */
@Entity
@Table(name = "export_invoice", catalog = "qlkh")
public class ExportInvoice implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Customer customer;
	private String name;
	private Date created;
	private byte status;
	private Set<ExportInvoiceDetails> exportInvoiceDetailses = new HashSet<ExportInvoiceDetails>(0);

	public ExportInvoice() {
	}

	public ExportInvoice(Account account, Customer customer, String name, Date created, byte status) {
		this.account = account;
		this.customer = customer;
		this.name = name;
		this.created = created;
		this.status = status;
	}

	public ExportInvoice(Account account, Customer customer, String name, Date created, byte status,
			Set<ExportInvoiceDetails> exportInvoiceDetailses) {
		this.account = account;
		this.customer = customer;
		this.name = name;
		this.created = created;
		this.status = status;
		this.exportInvoiceDetailses = exportInvoiceDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_acc", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cus", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exportInvoice")
	public Set<ExportInvoiceDetails> getExportInvoiceDetailses() {
		return this.exportInvoiceDetailses;
	}

	public void setExportInvoiceDetailses(Set<ExportInvoiceDetails> exportInvoiceDetailses) {
		this.exportInvoiceDetailses = exportInvoiceDetailses;
	}

}
