package com.demo.entities;
// Generated Jan 20, 2022, 9:21:20 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImportInvoicesDetails generated by hbm2java
 */
@Entity
@Table(name = "import_invoices_details", catalog = "qlkh")
public class ImportInvoicesDetails implements java.io.Serializable {

	private ImportInvoicesDetailsId id;
	private ImportInvoices importInvoices;
	private Product product;
	private double price;
	private int quantity;

	public ImportInvoicesDetails() {
	}

	public ImportInvoicesDetails(ImportInvoicesDetailsId id, ImportInvoices importInvoices, Product product,
			double price, int quantity) {
		this.id = id;
		this.importInvoices = importInvoices;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idInvoice", column = @Column(name = "id_invoice", nullable = false)),
			@AttributeOverride(name = "idPro", column = @Column(name = "id_pro", nullable = false)) })
	public ImportInvoicesDetailsId getId() {
		return this.id;
	}

	public void setId(ImportInvoicesDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_invoice", nullable = false, insertable = false, updatable = false)
	public ImportInvoices getImportInvoices() {
		return this.importInvoices;
	}

	public void setImportInvoices(ImportInvoices importInvoices) {
		this.importInvoices = importInvoices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pro", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
