package com.demo.entities;
// Generated Jan 20, 2022, 9:21:20 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImportInvoicesDetailsId generated by hbm2java
 */
@Embeddable
public class ImportInvoicesDetailsId implements java.io.Serializable {

	private int idInvoice;
	private int idPro;

	public ImportInvoicesDetailsId() {
	}

	public ImportInvoicesDetailsId(int idInvoice, int idPro) {
		this.idInvoice = idInvoice;
		this.idPro = idPro;
	}

	@Column(name = "id_invoice", nullable = false)
	public int getIdInvoice() {
		return this.idInvoice;
	}

	public void setIdInvoice(int idInvoice) {
		this.idInvoice = idInvoice;
	}

	@Column(name = "id_pro", nullable = false)
	public int getIdPro() {
		return this.idPro;
	}

	public void setIdPro(int idPro) {
		this.idPro = idPro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportInvoicesDetailsId))
			return false;
		ImportInvoicesDetailsId castOther = (ImportInvoicesDetailsId) other;

		return (this.getIdInvoice() == castOther.getIdInvoice()) && (this.getIdPro() == castOther.getIdPro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdInvoice();
		result = 37 * result + this.getIdPro();
		return result;
	}

}
