package com.demo.entities;
// Generated Jan 20, 2022, 9:21:20 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImportInvoices generated by hbm2java
 */
@Entity
@Table(name = "import_invoices", catalog = "qlkh")
public class ImportInvoices implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Supplier supplier;
	private String name;
	private Date created;
	private byte status;
	private Set<ImportInvoicesDetails> importInvoicesDetailses = new HashSet<ImportInvoicesDetails>(0);

	public ImportInvoices() {
	}

	public ImportInvoices(Account account, Supplier supplier, String name, Date created, byte status) {
		this.account = account;
		this.supplier = supplier;
		this.name = name;
		this.created = created;
		this.status = status;
	}

	public ImportInvoices(Account account, Supplier supplier, String name, Date created, byte status,
			Set<ImportInvoicesDetails> importInvoicesDetailses) {
		this.account = account;
		this.supplier = supplier;
		this.name = name;
		this.created = created;
		this.status = status;
		this.importInvoicesDetailses = importInvoicesDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_acc", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sup", nullable = false)
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importInvoices")
	public Set<ImportInvoicesDetails> getImportInvoicesDetailses() {
		return this.importInvoicesDetailses;
	}

	public void setImportInvoicesDetailses(Set<ImportInvoicesDetails> importInvoicesDetailses) {
		this.importInvoicesDetailses = importInvoicesDetailses;
	}

}
