package com.demo.entities;
// Generated Jan 20, 2022, 9:21:20 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "qlkh")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private double price;
	private int quantity;
	private int status;
	private String description;
	private Date created;
	private Set<ImportInvoicesDetails> importInvoicesDetailses = new HashSet<ImportInvoicesDetails>(0);
	private Set<ExportInvoiceDetails> exportInvoiceDetailses = new HashSet<ExportInvoiceDetails>(0);

	public Product() {
	}

	public Product(Category category, String name, double price, int quantity, int status, String description,
			Date created) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.status = status;
		this.description = description;
		this.created = created;
	}

	public Product(Category category, String name, double price, int quantity, int status, String description,
			Date created, Set<ImportInvoicesDetails> importInvoicesDetailses,
			Set<ExportInvoiceDetails> exportInvoiceDetailses) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.status = status;
		this.description = description;
		this.created = created;
		this.importInvoicesDetailses = importInvoicesDetailses;
		this.exportInvoiceDetailses = exportInvoiceDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ImportInvoicesDetails> getImportInvoicesDetailses() {
		return this.importInvoicesDetailses;
	}

	public void setImportInvoicesDetailses(Set<ImportInvoicesDetails> importInvoicesDetailses) {
		this.importInvoicesDetailses = importInvoicesDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ExportInvoiceDetails> getExportInvoiceDetailses() {
		return this.exportInvoiceDetailses;
	}

	public void setExportInvoiceDetailses(Set<ExportInvoiceDetails> exportInvoiceDetailses) {
		this.exportInvoiceDetailses = exportInvoiceDetailses;
	}

}
